FORMAT: 1A
HOST: https://gateway.workdesk.esenyun.com:9091

# 一森云JS-SDK接口

### 调用jsapi用户授权接口,取得用户的授权码

```
XuntongJSBridge.call('oauthConfirm', {'ticket':'{ticketId}'},      function(result){
  alert("结果："+JSON.stringify(result));
});

```

### 调用扫描二维码

```
XuntongJSBridge.call('qrcodeScan', {'type':'qrcode'},      function(result){
  alert("结果："+JSON.stringify(result));
});

```

# Group JS需要调用的API

## 获得授权码 [POST /esenopenplatform/openapi/oauth/authorize]
用户打开第三方APP时以自己的身份登录后调用，生成authorization_code 临时生成

+ Request

    + Headers
    
            Authorization: Bearer {access_token}
            
    + Body
    
            {
                "ticket": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
            }

+ Response 200 (application/json)

    + Body

            {
                "code": "xxxxxxxxxxx"
            }